services:
  zenvy_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: zenvy_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "9000"  # PHP-FPM écoute sur ce port
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - zenvy_db  # Suppression de la dépendance inutile à Nginx

  zenvy_nginx:
    image: nginx:alpine
    container_name: zenvy_nginx
    restart: always
    ports:
      - "8000:80"  # Nginx sert les requêtes sur le port 8000
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - zenvy_app  # Nginx dépend de PHP-FPM, mais pas l'inverse

  zenvy_db:
    image: mysql:8
    container_name: zenvy_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:


